name: Server
on:
 push:
   paths:
     - 'server/**'
     - '.github/workflows/server.yml'
 pull_request:
   paths:
     - 'server/**'
     - '.github/workflows/server.yml'
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['8', '11', '17']
    name: Java ${{ matrix.Java }} Test
    steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Setup Java
       uses: actions/setup-java@v2
       with:
         distribution: 'zulu'
         java-version: ${{ matrix.java }}
         cache: gradle
     - name: Test
       run: cd server && ./gradlew test
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 8
          cache: gradle
      - name: Lint
        run: cd server && ./gradlew lintKotlin
