name: Web - Build
on:
  push:
    branches:
      - master
    paths:
      - 'web/**'
      - '.github/workflows/web-build.yml'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Build
        run: cd web && yarn && yarn build && zip -j w3web.zip -r dist
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: web/v${{ github.run_number }}
          files: |
            web/w3web.zip
