name: Web
on:
  pull_request:
    paths:
      - 'web/**'
      - '.github/workflows/web.yml'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Lint
        run: cd web && yarn && yarn lint
